# Generated by Django 4.0.4 on 2022-05-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_hotelsik'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirm_reservation',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
